// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/layout/discover/Banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GoTop: typeof import('./src/components/common/goTop.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Image: typeof import('./src/components/common/Image.vue')['default']
    Iyric: typeof import('./src/components/common/Iyric.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
    PlayerAction: typeof import('./src/components/layout/playerBar/PlayerAction.vue')['default']
    PlayerBar: typeof import('./src/components/layout/playerBar/index.vue')['default']
    PlayerController: typeof import('./src/components/layout/playerBar/PlayerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/playerBar/PlayerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/playerBar/PlayerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/playerBar/PlayerVolumeSlider.vue')['default']
    PlayList: typeof import('./src/components/layout/playList/PlayList.vue')['default']
    PlayListSongItem: typeof import('./src/components/layout/playList/PlayListSongItem.vue')['default']
    PPlayerSlider: typeof import('./src/components/layout/playerBar/pPlayerSlider.vue')['default']
    Scroll: typeof import('./src/components/common/scroll.vue')['default']
    SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
    SongIyric: typeof import('./src/components/common/song-Iyric.vue')['default']
    SongLyric: typeof import('./src/components/common/SongLyric.vue')['default']
    SongSheet: typeof import('./src/components/layout/discover/songSheet.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
}

export { }
