<!--
 * @Author: zyh
 * @Date: 2022-03-23 12:58:20
 * @LastEditors: zyh
 * @LastEditTime: 2022-03-23 14:42:25
 * @FilePath: \music-item\src\views\Discover\index.vue
 * @Description: 发现
 * 
 * Copyright (c) 2022 by 穿越, All Rights Reserved. 
-->
<template>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
  <div>discover</div>
</template>

<script>
export default {
  name: "Discover",
};
</script>

<style></style>
